# Generated by Django 3.2 on 2024-09-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/default_avatar.jpg', null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
