# Generated by Django 3.2 on 2024-09-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_applicationuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/', verbose_name='Аватар'),
        ),
    ]
