# Generated by Django 3.2 on 2024-08-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240828_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/avatars/', verbose_name='Аватар'),
        ),
    ]
