# Generated by Django 3.2 on 2024-08-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_applicationuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='applicationuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/default_avatar.jpg', upload_to='media/users/', verbose_name='Аватар'),
        ),
    ]
