# Generated by Django 3.2 on 2024-08-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240829_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationuser',
            name='avatar',
            field=models.ImageField(blank=True, default='media/users/default_avatar.jpg', null=True, upload_to='media/users/', verbose_name='Аватар'),
        ),
    ]
